# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += MapExe/MapExe.pro \
    /../LabExe/src/labexe.pro \
    /../MapExe-Plugins/PluginProjects/WebPagePlugin/WebPagePlugin.pro \
    /../MapExe-Plugins/UserProjects/PicturePlugin/PicturePlugin.pro \
    /../MapExe-Plugins/UserProjects/TextPlugin/TextPlugin.pro \
    /../MapExe-Plugins/UserProjects/AudioPlayerPlugin/AudioPlayerPlugin.pro \
    /src/LabExeGraphicsMap.pro
