# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += MapExe/MapExe.pro \
    ../../LabExe/src/labexe.pro \
    ../../MapExe-Plugins/UserProjects/WebPagePlugin/WebPagePlugin.pro \
    ../../MapExe-Plugins/UserProjects/PicturePlugin/PicturePlugin.pro \
    ../../MapExe-Plugins/UserProjects/TextPlugin/TextPlugin.pro \
    ../../MapExe-Plugins/UserProjects/AudioPlayerPlugin/AudioPlayerPlugin.pro \
    ../../MapExe-Plugins/UserProjects/PdfPlugin/PdfPlugin.pro \
    ../../MapExe-Plugins/UserProjects/GmailConversationPlugin/GmailConversationPlugin.pro \
    ../src/LabExeGraphicsMap.pro
