#ifndef LABEXEGRAPHICSMAP_GLOBAL_H
#define LABEXEGRAPHICSMAP_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LABEXEGRAPHICSMAP_LIB
# define LABEXEGRAPHICSMAP_EXPORT Q_DECL_EXPORT
#else
# define LABEXEGRAPHICSMAP_EXPORT Q_DECL_IMPORT
#endif

#endif // LABEXEGRAPHICSMAP_GLOBAL_H
